name: Lint PR name

on:
  pull_request:
    branches: master
    types: [ opened, edited, synchronize, reopened ]

jobs:

  lint-PR-name:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Install Dependencies
        run: npm install @commitlint/config-conventional

      - uses: JulienKode/pull-request-name-linter-action@v0.2.0
        with:
          configuration-path: '.github/commitlint.config.js'
